### ISSUE TITLE
Inquiry about Band Order for Sentinel-2 Data

### ISSUE THREAD

**Issue by joannasta** [isaaccorley/hydro-foundation-model#4]
Hello,

I appreciate the nice work on this project! However, I noticed that information about the wavelengths is not provided. This is why I would like to inquire about the order of the bands used in the Sentinel-2 dataset for Hydro applications. Specifically, I am interested in:

1. The specific order of the bands.
2. If there is a script available that indicates which bands are used and in what order.
3.Information on the tools used to stack the bands.

Thank you for your help !:)

Best,

Joanna

**Comment by isaaccorley** [comment]
We used the Sentinel-2 L2A STAC collection from the Planetary Computer. The bands are: (B01, B02, B03, B04, B05, B06, B07, B08, B8A, B09, B11, B12)

We used stackstac and rioxarray to read and write the images to geotiffs.

**Comment by joannasta** [comment]
Thanks for the answer! It might be helpful to include this information in the README for future users. Clarifying the band ordering there could save others from potential confusion.

**Comment by isaaccorley** [comment]
I've added this info to the readme. Thanks!
