### ISSUE TITLE
Discrepancy in Dataset Size 

### ISSUE THREAD

**Issue by joannasta** [isaaccorley/hydro-foundation-model#5]
Hello,

I noticed a discrepancy in the README regarding the dataset size. The README states that the dataset consists of 50,000 Sentinel-2 patches, but when I extract the dataset, I receive  a bit more than 100,000 patches.

Could you please explain to me this difference?

Thank you very much!

**Comment by isaaccorley** [comment]
Yes the readme is old. We trained on ~100k patches

**Comment by isaaccorley** [comment]
I've updated the readme
